---
title: "Data exploration patient 5"
editor: visual
execute: 
  freeze: true
---

```{r}
library(grid)
library(gridExtra)
library(viridis)
library(ggplot2)
library(stringr)
library(dendextend)
devtools::load_all("../../../COTAN/")
```

# Ileum samples

```{r}
out_dir <- "../../Crohn_disease/data/04_cluster_identification/"
sample.id = "patient5_ileum"

obj <- readRDS(paste0("../../Crohn_disease/data/03_clustred_data/",sample.id,"_merged_cotan.RDS"))

srt <- readRDS(paste0("../data/03_clustred_data/Seurat_obj_",sample.id,"_with_cotan_clusters_merged.RDS"))
#obj <- readRDS(paste0("../../Crohn_disease/data/03_clustred_data/",sample.id,".cotan.clustered.RDS"))
srt <- SetIdent(srt, value = srt@meta.data$cotan)
```

cluster assignment with expression increment

```{r}
expression.cl <- read.csv(paste0(out_dir,sample.id,"_expression_clusters.csv"),row.names = 1)
markers <- readxl::read_excel("../../Marker_genes.xlsx",sheet = 2)
markers <- as.list(markers)
markers <- markers[2:length(markers)]
for (nv in names(markers)) {
  markers[[nv]] <- unique(markers[[nv]][!is.na(markers[[nv]])])
}

COEX.markers <- extract.coex(object = obj,genes = unlist(markers)[unlist(markers,) %in% rownames(obj@raw)])

```

```{r}
good.markers <- NA
for (v in colnames(COEX.markers)) {
  max.coex <- max(COEX.markers[!rownames(COEX.markers) %in% v,v])
  corr.gene <- rownames(which(COEX.markers == max.coex,arr.ind = T))
  gene.pval.adj <- p.adjust(pval.markers[corr.gene,v],n = dim(pval.markers)[1]**2/2)
  if (max.coex >= 0 & any(gene.pval.adj < 0.05)) {
    #print(paste0(v," max coex ",max.coex))  
    good.markers <- c(good.markers,v)
  }
}

for (m in names(markers)) {
  markers[[m]] <- markers[[m]][markers[[m]] %in% good.markers]
}


to.keep <- NA
for (v in 1:length(markers)) {
  #print(markers[[v]])
  if (length(markers[[v]])>0) {
    to.keep <- c(to.keep,v)
  }
}
to.keep <- to.keep[!is.na(to.keep)]

markers <- markers[to.keep]
markers

ISG.genes <- read.csv("../../ISG_fixed.txt",header = T)
colnames(ISG.genes) <- "genes"
markers$ISG <- ISG.genes$genes
```

```{r}
df <- as.data.frame(matrix(nrow = length(names(markers)),ncol = ncol(expression.cl)))
rownames(df) <- names(markers)
colnames(df) <- colnames(expression.cl)
df2 <- df

teta <- -1/0.1 * (log(0.25))
#not_ass_clusters <- NA
for (ro in colnames(df)) {
  for (m in names(markers)) {
    #print(m)
    #pv <- p_value[unlist(markers[[m]]),ro]
    #co <- obj@cluster_data[unlist(markers[[m]]),ro]
    ex <- expression.cl[rownames(expression.cl) %in% markers[[m]],ro]
    ex[ex < 0 & !is.na(ex)] <- 0
    
    ex <- 1-exp(- teta * ex)
    n.markers <- sum(rownames(obj@raw) %in% markers[[m]])
    df[m,ro] <- sum(ex,na.rm = T)/n.markers
    df2[m,ro]<- paste0(round(sum(ex,na.rm = T),digits = 1),"/",n.markers)
  }
}
#write.csv(df,file = paste(out_dir,sample.id,"_markers_clusters_expression.csv", sep = ""))

df <- round(df,digits = 2)
df <- df[,2:ncol(df)]


df2 <- df2[,2:ncol(df2)]
df2
```

```{r}
cluster_data <- getClusterizationData(obj)[["coex"]]

######## This is the best: cosine dissimilarity
Matrix <- as.matrix(t(cluster_data))
sim <- Matrix / sqrt(rowSums(Matrix * Matrix))
sim <- sim %*% t(sim)
D_sim <- as.dist(1 - sim)
tree <- hclust(D_sim,method = "ward.D2")

```

```{r}
dend <- as.dendrogram(tree)
#colnames(df) <- str_remove_all(colnames(df), pattern = "cl.")
cut = cutree(tree, k = 9)
dend =branches_color(dend,k=9,col=c("#4DBBD5FF","#91D1C2FF","#E64B35FF","gray80","#3C5488FF","#F39B7FFF","gray80"),groupLabels = T)
dend =color_labels(dend,k=9)

plot(dend)
```

```{r,fig.width=15}

col_fun = colorRamp2(c(0, 1), c( "lightblue", "red"))
Heatmap(df, rect_gp = gpar(col = "white", lwd = 1),
        cluster_rows = F,
        #cluster_columns = FALSE,
        show_heatmap_legend = F,
         col = col_fun,
        column_dend_height = unit(4, "cm"),
        row_dend_width
        = unit(4, "cm"),
        #width =  unit(24, "cm"),
        #height = unit(6, "cm"),
        cluster_columns = dend,
        row_names_gp = gpar(fontsize = 7),
        column_names_gp = gpar(fontsize = 7),
        cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.1f", df[i, j]), x, y, gp = gpar(fontsize = 5))
},
left_annotation = rowAnnotation(foo = anno_block(gp = gpar(fill = 2:4),
        labels = c("group1", "group2", "group3","","","",""), 
        labels_gp = gpar(col = "white", fontsize = 10))),
    row_km = 7
)
```

```{r,fig.width=20}
library(dplyr)
library(stringr)

#clusters <- colnames(obj@cluster_data)


cell.metadata <- srt@meta.data
cell.metadata <- cbind(cell.metadata,obj@nu[rownames(cell.metadata)])
colnames(cell.metadata)[dim(cell.metadata)[2]] <-  "nu"


if (!(all(unique(cell.metadata$cotan) %in% unique(obj@clusters)) &
    all(unique(obj@clusters) %in% unique(cell.metadata$cotan))) | 
    any(is.na(cell.metadata$cotan))) {
  print("Problems")
  
}


clusters <- t(table(cell.metadata[,c("orig.ident","cotan")]))
clusters <- as.data.frame(clusters)
clusters$cotan <- paste0("cl.",clusters$cotan)

clusters$nu_mean <- NA
for (cl in unique(clusters$cotan)) {
  cln <- str_split(cl,pattern = "[.]",simplify = T)[2]
  for (sp in unique(clusters$orig.ident)) {
    clusters[clusters$cotan == cl & clusters$orig.ident == sp,]$nu_mean <- 
      mean(cell.metadata[cell.metadata$orig.ident == sp & cell.metadata$cotan == cln,]$nu)
  }
}

clusters$cotan <- factor(clusters$cotan,levels = labels(dend))
ggplot(clusters, aes(x = cotan, y = Freq, fill = orig.ident)) +  # Create stacked bar chart
  geom_bar(stat = "identity",position = "dodge")+
  geom_text(aes(label = round(nu_mean,digits=1)), position=position_dodge(width=0.5), vjust=-0.5) +
  theme(legend.position = "none") 

```

```{r,fig.width=20,fig.height=30}
pl <- plot_general.heatmap(prim.markers = markers$`T cell genes`,markers.list = markers[c(1,6:9)],condition =  paste0(sample.id,".clustered.merged"),dir = "../data/03_clustred_data/",p_value = 1e-10,symmetric = F)
```

```{r}
pl1 <- plot_general.heatmap(prim.markers = markers$`B cell genes`,markers.list = c("ID2","ITGAE","PRF1","GZMB","IFNG","CD3G","CD2","CD7","BCL11B","TBX21","GATA3", "ZBTB16"),condition =  paste0(sample.id,".clustered.merged"),dir = "../data/03_clustred_data/",p_value = 1e-5,symmetric = T)

```
