project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - IBD/results/01A_Seurat_import_clean.qmd
    - Crohn_disease/results/01_cleaning_patient5_NB.qmd
    - Crohn_disease/results/01_cleaning_patient7_NB.qmd

 
website:
  title: "RNA editing project"
  navbar: 
    background: primary
    search: true
  
    left: 
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

    
  sidebar:
    style: docked
    contents:
      - section: "IBD dataset"
        contents:
          - href: IBD/results/01A_Seurat_import_clean.qmd
            text: "Seurat cleaning"
      
      - section: "Crohn disease dataset"
        contents:
            
            - section: "COTAN cleaning"
              contents:
                - href: Crohn_disease/results/01_cleaning_patient5_NB.qmd
                  text: "patient 5 ileum"
                - href: Crohn_disease/results/01_cleaning_patient7_NB.qmd
                  text: "patient 7 ileum"
                  
            - section: "Data exploration & Cluster identification"
            
                  
            - section: "Summary and Conclusion"
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

  


